### PR TITLE
Chapterlist DecodingError fix

### PR DESCRIPTION
**Pull request by K1NXZ**
Fixed a bug where an DecodingError occured when trying to fetch a specific mangas chapterList, because members are delivered empty from the api in that case.

### CODE REVIEW

**Comment by JRomainG** [comment]
Thanks for the pull request!

I had a look at the API to understand why this code no longer worked, and it seems to be related to breaking changes introduced recently:

> - ScanlationGroup will no longer have a leader and members array inside its attributes and will no longer return relationships of type user. Instead, the leader will be returned as an extendable relationship of type "leader", the members will no longer be returned inside the attributes, but as extendable relationships of type "member". Both are user entities (similar to how the type "artist" is an "author" entity).
> - CustomList will no longer have an owner attribute, instead it will be returned as a relationship of type "user". Its manga relationships will also be expandable by Reference Expansion. 

This means that we should actually just get rid of the `MDGroup.leader` and `MDGroup.members` attributes. That way, we also don't need to redefine the `init` method of `MDGroup`.

Would you like to edit the PR to implement these changes instead? As far as I can tell, this shouldn't break any of the tests you introduced.

Apart from that, I've just got a few minor quibbles:

* It seems like your editor is configured to indent using tabs, whereas the rest of the code is indented using 4 spaces, which introduces some inconsistencies and noise in the diff
* The PR contains changes to `MangaDexLib.xcodeproj/project.pbxproj` because of the `Secret.bundle` file, it would be nice to remove those changes as they are not really relevant to this PR
* I like to add comments to methods and attributes for the documentation, so it would be nice to add a small phrase for `MDObjectType.leader` and `MDObjectType.member`

If you'd like, I can edit the PR to handle those few changes as it's quite easy to do

**Comment by K1NXZ** [comment]
> > * ScanlationGroup will no longer have a leader and members array inside its attributes and will no longer return relationships of type user. Instead, the leader will be returned as an extendable relationship of type "leader", the members will no longer be returned inside the attributes, but as extendable relationships of type "member". Both are user entities (similar to how the type "artist" is an "author" entity).
> > * CustomList will no longer have an owner attribute, instead it will be returned as a relationship of type "user". Its manga relationships will also be expandable by Reference Expansion.

Where do I find this kind of information? I didn't see that on the MangaDex docs.

> If you'd like, I can edit the PR to handle those few changes as it's quite easy to do

Go ahead! :)

Btw great work on the API. I was about to implement a client myself, then I saw your project and rolled with it.

**Comment by JRomainG** [comment]
You can find this information on the announcement Discord group of MangaDex (using [this invite](https://discord.com/invite/vkW47gN5TY)). The `#v5-changelog` channel contains information about the state of the official API. I find it very useful to keep track of changes, especially since it is still under heavy development.

I'll take care of tweaking the PR a bit then and merge it, thanks again for the contribution!
I'm really glad the project was of help to you, I haven't had time to implement all the latest changes to the API but hopefully it still is useful enough :)

**Comment by JRomainG** [comment]
Merged manually in 24e6a0a7bd8ea1f8c21a18af7eaeb266e32b6b00

**Pull request closed without merging**
